<?php echo $this->doctype(); ?>
 
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Rabbit Internet Test'))->setSeparator(' - ')->setAutoEscape(false) ?>
 
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
 
        <!-- styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
 
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/main.js')
                                      ->prependFile($this->basePath() . '/js/bootbox.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.googlemap.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

        <script type="text/javascript" src="//www.google.com/jsapi"></script>
        <script type="text/javascript">
            google.load("maps", "3.4", {
                other_params: "sensor=false"
            });
        </script>
        
        
    </head>
    <body>
        <div>
            <div>
                <div>
                    <a data-toggle="collapse" data-target=".nav-collapse">
                        <span></span>
                        <span></span>
                        <span></span>
                    </a>
                </div>
            </div>
        </div>
        <div>
            
            <?php echo $this->content; ?>
            <hr>
            <footer>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>