
<div class="row">
    <div class="col-md-12">    
        <div id="map"></div>
            <script type="text/javascript">
              $(function() {
                $("#map").googleMap({
                  zoom: 10, // Set Zoomlevel to 10
                  coords: [ 13.7522, 100.4939], // Centre the map on Bangkok for Testing
                  type: "ROADMAP" // Map type, set to Roadmap.
                });

                  
              });   
            </script>
        
    </div>
</div>
<div class="row" style="position:fixed;bottom:0;width:100%;">
    <form name="search" method="post" action"" >
        <div class="col-md-6">
                <input type="text" placeholder="City Name" id="address" name="address" style="width:95%; border:1px solid black; padding:3px;"/>
        </div>

        <input type="submit" style="float:left;padding:4px;background:red;text-align:center;color:#fff;" class="col-md-3" value="Search"></input>
        <input type="button" id="history" style="margin-left:5px;margin-right:-5px;background:red;padding:4px;color:#fff;text-align:center" class="col-md-3" value="History"></div>
    </form>
</div>
