
<div class="row">
    <div id="location">Tweets about <?php echo $this->address; ?></div>
    <div class="col-md-12">    
        <div id="map"></div>
            <script type="text/javascript">
              $(document).ready(function() {
                $("#map").googleMap({
                  zoom: 10, // Set Zoomlevel to 10
                  coords: [<?php echo $this->map_lat . ',' . $this->map_long; ?>], // Centre the map on geocoord provided by Zend
                  type: "ROADMAP" // Map type, set to Roadmap.
                });

                var errMsg = "<?php echo $this->errorMsg; ?>";
                if(errMsg!='') {
                    bootbox.alert(errMsg, function() {
                    });
                } else {
                    var addresses = [];
                    if(localStorage && localStorage.getItem('addresses')){
                        addresses = JSON.parse(localStorage.getItem('addresses'));
                    };
                    var address = '<?php echo $this->address; ?>';
                    addresses.push(address);
                    localStorage.setItem( 'addresses', JSON.stringify(addresses) );
                    
                    var markerArray = <?php echo json_encode($this->markers); ?>;
                    $.each(markerArray, function(i, v) {
                        $("#map").addMarker({
                              coords: [markerArray[i][0],markerArray[i][1]], // GPS coords
                              icon: markerArray[i][2],
                              text: markerArray[i][3], 
                              title:  markerArray[i][4]
                        }); 
                    }); 
                };
                  
                $('input#history').click(function() { 
                    if(localStorage && localStorage.getItem('addresses')){
                        var formattedAddresses = '', count=0;
                        addresses = JSON.parse(localStorage.getItem('addresses'));

                        $.each(addresses, function(i, v) {
                            if(formattedAddresses.indexOf(v)==-1) {
                                formattedAddresses += count + ": " + v + '<br />';
                                count++;
                            }
                        });
                    } else { 
                        formattedAddresses = 'No Locations in History';
                    };
                    bootbox.alert(formattedAddresses);           
                });
                  
            });   
        </script>
        
    </div>
</div>
<div class="row" style="position:fixed;bottom:0;width:100%;">
    <form name="search" method="post" action"" >
        <div class="col-md-6">
                <input type="text" placeholder="City Name" id="address" name="address" style="width:95%; border:1px solid black; padding:3px;"/>
        </div>

        <input type="submit" style="float:left;padding:4px;background:red;text-align:center;color:#fff;" class="col-md-3" value="Search"></input>
        <input type="button" id="history" style="margin-left:5px;margin-right:-5px;background:red;padding:4px;color:#fff;text-align:center" class="col-md-3" value="History"></div>
    </form>
</div>
